### ISSUE TITLE
AWS - Connection Keys

### ISSUE THREAD

**Issue by app-generator** [app-generator/deploypro-docs#1]
The user needs to be informed of where to get the keys from AWS. 
`Step by Step` guide 

> DOCS Page: [AWS - Generate Credentials](https://github.com/app-generator/deploypro-docs/blob/main/docs/aws/generate-credentials.md)

This information is used/referred to when the user connects his AWS account:

![image](https://github.com/app-generator/deploypro-docs/assets/51070104/cd6156b3-6ebd-437b-ba30-28cb1b0ed503)

@sgnd please take a look.

TY!

**Comment by app-generator** [comment]
Hello @sgnd
Please proceed with this item. The page is here: 
 
https://github.com/app-generator/deploypro-docs/blob/main/docs/aws/generate-credentials.md

**Comment by sgnd** [comment]
@app-generator ready for test

**Comment by app-generator** [comment]
Validated. Closing.
