### ISSUE TITLE
AWS - Platform INTRO

### ISSUE THREAD

**Issue by app-generator** [app-generator/deploypro-docs#3]
The AWS section needs to be updated to provide a general introduction to the AWS Provider.

> DOCS Page: [AWS - Intro](https://github.com/app-generator/deploypro-docs/blob/main/docs/aws/intro.mdx)

<br />

## Sections:

- Short intro
- The most popular AWS services
- How to create an account
- Core Settings that require attention for a beginner 
- How to create a new VPS
- How to park a domain
- Cost Control 
  - how to monitor the monthly costs
  - how to lower the costs 

Plus other things that might help a beginner to start using AWS. 

Audience: Beginners, Medium Skilled Devs 

@sgnd Please take a look.
TY!

**Comment by auliaromadon** [comment]
hello @app-generator , may i know where i should put the custom domain guide?

**Comment by auliaromadon** [comment]
for the new change in the structure of the docs, do the 50 samples is similar to the content inside "create a static app" file?

**Comment by app-generator** [comment]
> for the new change in the structure of the docs, do the 50 samples is similar to the content inside "create a static app" file?

Sorry, please rephrase this. 

I will not update anymore the current structure. The numbering is used just to force a desired order, thing currently unsupported by Docusaurus.

**Comment by app-generator** [comment]
> hello @app-generator , may I know where I should put the custom domain guide?

Inside each provider, even the content is somehow duplicated. 
But, please postpone this documentation because is somehow `advanced` and we might address it for paying users. 

I will get back to you asap (hope tomorrow 14. Aug) with the new DOCS items that need urgent attention  

P.S. Ping me anytime in Discord. I'm almost 24/7 there. 

TY!

**Comment by sgnd** [comment]
@app-generator some information already finish, custom domain and cost control will postpone

**Comment by app-generator** [comment]
Validated. Closing.
