### ISSUE TITLE
AWS - Deploy React (step by step guide)

### ISSUE THREAD

**Issue by app-generator** [app-generator/deploypro-docs#4]
The DOCS needs to provide a `step by step` guide regarding the deployment of a simple React project. 

As input, this reference repo needs to be used: 

https://github.com/app-generator/deploypro-react

@auliaromadon please take a look.
TY!

**Comment by auliaromadon** [comment]
Hello, just finished the docs https://www.docs.deploypro.dev/aws/create-static-app
Some parts and capture will be added just like:
- Capture from Actions Tab on GH repo after creating an app
- Capture for the successful deployment --> Visit the app domain
- and more info about Custom Domain

let me know if you have some considerations :)

**Comment by app-generator** [comment]
Ty @auliaromadon 

I will pull the changes and review them. 

Keep up the good work. 
🚀🚀

**Comment by sgnd** [comment]
@app-generator ready for test

**Comment by app-generator** [comment]
Validated. Closing.
